// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuth = "auth"

// Auth mapped from table <auth>
type Auth struct {
	MbID   *string `gorm:"column:mb_id;type:VARCHAR(20)" json:"mb_id"`
	AuMenu *string `gorm:"column:au_menu;type:VARCHAR(20)" json:"au_menu"`
	AuAuth *string `gorm:"column:au_auth;type:VARCHAR(255)" json:"au_auth"`
}

// TableName Auth's table name
func (*Auth) TableName() string {
	return TableNameAuth
}
