// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/dukhyungkim/gonuboard/config"
	"time"
)

const TableNameAutosave = "autosave"

// Autosave mapped from table <autosave>
type Autosave struct {
	AsID       *int32     `gorm:"column:as_id;type:INTEGER" json:"as_id"`
	MbID       *string    `gorm:"column:mb_id;type:VARCHAR(20)" json:"mb_id"`
	AsUID      *int64     `gorm:"column:as_uid;type:BIGINT" json:"as_uid"`
	AsSubject  *string    `gorm:"column:as_subject;type:VARCHAR(255)" json:"as_subject"`
	AsContent  *string    `gorm:"column:as_content;type:TEXT" json:"as_content"`
	AsDatetime *time.Time `gorm:"column:as_datetime;type:DATETIME" json:"as_datetime"`
}

// TableName Autosave's table name
func (*Autosave) TableName() string {
	return config.Global.DbTablePrefix + TableNameAutosave
}
