package model

const TableNameConfig = "config"

// Config mapped from table <config>
type Config struct {
	CfID                  uint   `gorm:"type:INTEGER;primaryKey;not null"`
	CfTitle               string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfTheme               string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfAdmin               string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfAdminEmail          string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfAdminEmailName      string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfAddScript           string `gorm:"type:TEXT;not null;default:''"`
	CfUsePoint            int    `gorm:"type:INTEGER;not null;default:0"`
	CfPointTerm           int    `gorm:"type:INTEGER;not null;default:0"`
	CfUseCopyLog          int    `gorm:"type:INTEGER;not null;default:0"`
	CfUseEmailCertify     int    `gorm:"type:INTEGER;not null;default:0"`
	CfLoginPoint          int    `gorm:"type:INTEGER;not null;default:0"`
	CfCutName             int    `gorm:"type:INTEGER;not null;default:0"`
	CfNickModify          int    `gorm:"type:INTEGER;not null;default:0"`
	CfNewSkin             string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfNewRows             int    `gorm:"type:INTEGER;not null;default:0"`
	CfSearchSkin          string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfConnectSkin         string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfFaqSkin             string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfReadPoint           int    `gorm:"type:INTEGER;not null;default:0"`
	CfWritePoint          int    `gorm:"type:INTEGER;not null;default:0"`
	CfCommentPoint        int    `gorm:"type:INTEGER;not null;default:0"`
	CfDownloadPoint       int    `gorm:"type:INTEGER;not null;default:0"`
	CfWritePages          int    `gorm:"type:INTEGER;not null;default:0"`
	CfMobilePages         int    `gorm:"type:INTEGER;not null;default:0"`
	CfLinkTarget          string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfBbsRewrite          int    `gorm:"type:INTEGER;not null;default:0"`
	CfDelaySec            int    `gorm:"type:INTEGER;not null;default:0"`
	CfFilter              string `gorm:"type:TEXT;not null;default:''"`
	CfPossibleIP          string `gorm:"type:TEXT;not null;default:''"`
	CfInterceptIP         string `gorm:"type:TEXT;not null;default:''"`
	CfAnalytics           string `gorm:"type:TEXT;not null;default:''"`
	CfAddMeta             string `gorm:"type:TEXT;not null;default:''"`
	CfMemberSkin          string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfUseHomepage         int    `gorm:"type:INTEGER;not null;default:0"`
	CfReqHomepage         int    `gorm:"type:INTEGER;not null;default:0"`
	CfUseTel              int    `gorm:"type:INTEGER;not null;default:0"`
	CfReqTel              int    `gorm:"type:INTEGER;not null;default:0"`
	CfUseHp               int    `gorm:"type:INTEGER;not null;default:0"`
	CfReqHp               int    `gorm:"type:INTEGER;not null;default:0"`
	CfUseAddr             int    `gorm:"type:INTEGER;not null;default:0"`
	CfReqAddr             int    `gorm:"type:INTEGER;not null;default:0"`
	CfUseSignature        int    `gorm:"type:INTEGER;not null;default:0"`
	CfReqSignature        int    `gorm:"type:INTEGER;not null;default:0"`
	CfUseProfile          int    `gorm:"type:INTEGER;not null;default:0"`
	CfReqProfile          int    `gorm:"type:INTEGER;not null;default:0"`
	CfRegisterLevel       int    `gorm:"type:INTEGER;not null;default:0"`
	CfRegisterPoint       int    `gorm:"type:INTEGER;not null;default:0"`
	CfIconLevel           int    `gorm:"type:INTEGER;not null;default:0"`
	CfUseRecommend        int    `gorm:"type:INTEGER;not null;default:0"`
	CfRecommendPoint      int    `gorm:"type:INTEGER;not null;default:0"`
	CfLeaveDay            int    `gorm:"type:INTEGER;not null;default:0"`
	CfSearchPart          int    `gorm:"type:INTEGER;not null;default:0"`
	CfEmailUse            int    `gorm:"type:INTEGER;not null;default:0"`
	CfEmailWrSuperAdmin   int    `gorm:"type:INTEGER;not null;default:0"`
	CfEmailWrGroupAdmin   int    `gorm:"type:INTEGER;not null;default:0"`
	CfEmailWrBoardAdmin   int    `gorm:"type:INTEGER;not null;default:0"`
	CfEmailWrWrite        int    `gorm:"type:INTEGER;not null;default:0"`
	CfEmailWrCommentAll   int    `gorm:"type:INTEGER;not null;default:0"`
	CfEmailMbSuperAdmin   int    `gorm:"type:INTEGER;not null;default:0"`
	CfEmailMbMember       int    `gorm:"type:INTEGER;not null;default:0"`
	CfEmailPoSuperAdmin   int    `gorm:"type:INTEGER;not null;default:0"`
	CfProhibitID          string `gorm:"type:TEXT;not null;default:''"`
	CfProhibitEmail       string `gorm:"type:TEXT;not null;default:''"`
	CfNewDel              int    `gorm:"type:INTEGER;not null;default:0"`
	CfMemoDel             int    `gorm:"type:INTEGER;not null;default:0"`
	CfVisitDel            int    `gorm:"type:INTEGER;not null;default:0"`
	CfPopularDel          int    `gorm:"type:INTEGER;not null;default:0"`
	CfOptimizeDate        string `gorm:"type:VARCHAR(10);not null;default:''"`
	CfUseMemberIcon       int    `gorm:"type:INTEGER;not null;default:0"`
	CfMemberIconSize      int    `gorm:"type:INTEGER;not null;default:0"`
	CfMemberIconWidth     int    `gorm:"type:INTEGER;not null;default:0"`
	CfMemberIconHeight    int    `gorm:"type:INTEGER;not null;default:0"`
	CfMemberImgSize       int    `gorm:"type:INTEGER;not null;default:0"`
	CfMemberImgWidth      int    `gorm:"type:INTEGER;not null;default:0"`
	CfMemberImgHeight     int    `gorm:"type:INTEGER;not null;default:0"`
	CfLoginMinutes        int    `gorm:"type:INTEGER;not null;default:0"`
	CfImageExtension      string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfFlashExtension      string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfMovieExtension      string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfFormmailIsMember    int    `gorm:"type:INTEGER;not null;default:0"`
	CfPageRows            int    `gorm:"type:INTEGER;not null;default:0"`
	CfMobilePageRows      int    `gorm:"type:INTEGER;not null;default:0"`
	CfVisit               string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfMaxPoID             int    `gorm:"type:INTEGER;not null;default:0"`
	CfStipulation         string `gorm:"type:TEXT;not null;default:''"`
	CfPrivacy             string `gorm:"type:TEXT;not null;default:''"`
	CfOpenModify          int    `gorm:"type:INTEGER;not null;default:0"`
	CfMemoSendPoint       int    `gorm:"type:INTEGER;not null;default:0"`
	CfMobileNewSkin       string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfMobileSearchSkin    string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfMobileConnectSkin   string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfMobileFaqSkin       string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfMobileMemberSkin    string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfCaptchaMp3          string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfEditor              string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfCertUse             int    `gorm:"type:INTEGER;not null;default:0"`
	CfCertFind            int    `gorm:"type:INTEGER;not null;default:0"`
	CfCertIpin            string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfCertHp              string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfCertSimple          string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfCertKgCd            string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfCertKgMid           string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfCertKcbCd           string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfCertKcpCd           string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfLgMid               string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfLgMertKey           string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfCertLimit           int    `gorm:"type:INTEGER;not null;default:0"`
	CfCertReq             int    `gorm:"type:INTEGER;not null;default:0"`
	CfSmsUse              string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfSmsType             string `gorm:"type:VARCHAR(10);not null;default:''"`
	CfIcodeID             string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfIcodePw             string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfIcodeServerIP       string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfIcodeServerPort     string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfIcodeTokenKey       string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfGooglShorturlApikey string `gorm:"type:VARCHAR(50);not null;default:''"`
	CfSocialLoginUse      int    `gorm:"type:INTEGER;not null;default:0"`
	CfSocialServicelist   string `gorm:"type:VARCHAR(255);not null;default:''"`
	CfPaycoClientid       string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfPaycoSecret         string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfFacebookAppid       string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfFacebookSecret      string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfTwitterKey          string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfTwitterSecret       string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfGoogleClientid      string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfGoogleSecret        string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfNaverClientid       string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfNaverSecret         string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfKakaoRestKey        string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfKakaoClientSecret   string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfKakaoJsApikey       string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfCaptcha             string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfRecaptchaSiteKey    string `gorm:"type:VARCHAR(100);not null;default:''"`
	CfRecaptchaSecretKey  string `gorm:"type:VARCHAR(100);not null;default:''"`
	Cf1Subj               string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf2Subj               string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf3Subj               string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf4Subj               string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf5Subj               string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf6Subj               string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf7Subj               string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf8Subj               string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf9Subj               string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf10Subj              string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf1                   string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf2                   string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf3                   string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf4                   string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf5                   string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf6                   string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf7                   string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf8                   string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf9                   string `gorm:"type:VARCHAR(255);not null;default:''"`
	Cf10                  string `gorm:"type:VARCHAR(255);not null;default:''"`
}

// TableName Config's table name
func (*Config) TableName() string {
	return Prefix + TableNameConfig
}
