// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFaqMaster = "faq_master"

// FaqMaster mapped from table <faq_master>
type FaqMaster struct {
	FmID             *int32  `gorm:"column:fm_id;type:INTEGER" json:"fm_id"`
	FmSubject        *string `gorm:"column:fm_subject;type:VARCHAR(255)" json:"fm_subject"`
	FmHeadHTML       *string `gorm:"column:fm_head_html;type:TEXT" json:"fm_head_html"`
	FmTailHTML       *string `gorm:"column:fm_tail_html;type:TEXT" json:"fm_tail_html"`
	FmMobileHeadHTML *string `gorm:"column:fm_mobile_head_html;type:TEXT" json:"fm_mobile_head_html"`
	FmMobileTailHTML *string `gorm:"column:fm_mobile_tail_html;type:TEXT" json:"fm_mobile_tail_html"`
	FmOrder          *int32  `gorm:"column:fm_order;type:INTEGER" json:"fm_order"`
}

// TableName FaqMaster's table name
func (*FaqMaster) TableName() string {
	return Prefix + TableNameFaqMaster
}
