// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroup = "group"

// Group mapped from table <group>
type Group struct {
	GrID        *string `gorm:"column:gr_id;type:VARCHAR(10)" json:"gr_id"`
	GrSubject   *string `gorm:"column:gr_subject;type:VARCHAR(255)" json:"gr_subject"`
	GrDevice    *string `gorm:"column:gr_device;type:VARCHAR(6)" json:"gr_device"`
	GrAdmin     *string `gorm:"column:gr_admin;type:VARCHAR(255)" json:"gr_admin"`
	GrUseAccess *int32  `gorm:"column:gr_use_access;type:INTEGER" json:"gr_use_access"`
	GrOrder     *int32  `gorm:"column:gr_order;type:INTEGER" json:"gr_order"`
	Gr1Subj     *string `gorm:"column:gr_1_subj;type:VARCHAR(255)" json:"gr_1_subj"`
	Gr2Subj     *string `gorm:"column:gr_2_subj;type:VARCHAR(255)" json:"gr_2_subj"`
	Gr3Subj     *string `gorm:"column:gr_3_subj;type:VARCHAR(255)" json:"gr_3_subj"`
	Gr4Subj     *string `gorm:"column:gr_4_subj;type:VARCHAR(255)" json:"gr_4_subj"`
	Gr5Subj     *string `gorm:"column:gr_5_subj;type:VARCHAR(255)" json:"gr_5_subj"`
	Gr6Subj     *string `gorm:"column:gr_6_subj;type:VARCHAR(255)" json:"gr_6_subj"`
	Gr7Subj     *string `gorm:"column:gr_7_subj;type:VARCHAR(255)" json:"gr_7_subj"`
	Gr8Subj     *string `gorm:"column:gr_8_subj;type:VARCHAR(255)" json:"gr_8_subj"`
	Gr9Subj     *string `gorm:"column:gr_9_subj;type:VARCHAR(255)" json:"gr_9_subj"`
	Gr10Subj    *string `gorm:"column:gr_10_subj;type:VARCHAR(255)" json:"gr_10_subj"`
	Gr1         *string `gorm:"column:gr_1;type:VARCHAR(255)" json:"gr_1"`
	Gr2         *string `gorm:"column:gr_2;type:VARCHAR(255)" json:"gr_2"`
	Gr3         *string `gorm:"column:gr_3;type:VARCHAR(255)" json:"gr_3"`
	Gr4         *string `gorm:"column:gr_4;type:VARCHAR(255)" json:"gr_4"`
	Gr5         *string `gorm:"column:gr_5;type:VARCHAR(255)" json:"gr_5"`
	Gr6         *string `gorm:"column:gr_6;type:VARCHAR(255)" json:"gr_6"`
	Gr7         *string `gorm:"column:gr_7;type:VARCHAR(255)" json:"gr_7"`
	Gr8         *string `gorm:"column:gr_8;type:VARCHAR(255)" json:"gr_8"`
	Gr9         *string `gorm:"column:gr_9;type:VARCHAR(255)" json:"gr_9"`
	Gr10        *string `gorm:"column:gr_10;type:VARCHAR(255)" json:"gr_10"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
