// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLogin = "login"

// Login mapped from table <login>
type Login struct {
	LoID       *int32     `gorm:"column:lo_id;type:INTEGER" json:"lo_id"`
	LoIP       *string    `gorm:"column:lo_ip;type:VARCHAR(100)" json:"lo_ip"`
	MbID       *string    `gorm:"column:mb_id;type:VARCHAR(20)" json:"mb_id"`
	LoDatetime *time.Time `gorm:"column:lo_datetime;type:DATETIME" json:"lo_datetime"`
	LoLocation *string    `gorm:"column:lo_location;type:TEXT" json:"lo_location"`
	LoURL      *string    `gorm:"column:lo_url;type:TEXT" json:"lo_url"`
}

// TableName Login's table name
func (*Login) TableName() string {
	return TableNameLogin
}
