// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMail = "mail"

// Mail mapped from table <mail>
type Mail struct {
	MaID         *int32     `gorm:"column:ma_id;type:INTEGER" json:"ma_id"`
	MaSubject    *string    `gorm:"column:ma_subject;type:VARCHAR(255)" json:"ma_subject"`
	MaContent    *string    `gorm:"column:ma_content;type:TEXT" json:"ma_content"`
	MaTime       *time.Time `gorm:"column:ma_time;type:DATETIME" json:"ma_time"`
	MaIP         *string    `gorm:"column:ma_ip;type:VARCHAR(255)" json:"ma_ip"`
	MaLastOption *string    `gorm:"column:ma_last_option;type:TEXT" json:"ma_last_option"`
}

// TableName Mail's table name
func (*Mail) TableName() string {
	return Prefix + TableNameMail
}
