// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMember = "member"

// Member mapped from table <member>
type Member struct {
	MbNo            *int32     `gorm:"column:mb_no;type:INTEGER" json:"mb_no"`
	MbID            *string    `gorm:"column:mb_id;type:VARCHAR(20)" json:"mb_id"`
	MbPassword      *string    `gorm:"column:mb_password;type:VARCHAR(255)" json:"mb_password"`
	MbName          *string    `gorm:"column:mb_name;type:VARCHAR(255)" json:"mb_name"`
	MbNick          *string    `gorm:"column:mb_nick;type:VARCHAR(255)" json:"mb_nick"`
	MbNickDate      *time.Time `gorm:"column:mb_nick_date;type:DATE" json:"mb_nick_date"`
	MbEmail         *string    `gorm:"column:mb_email;type:VARCHAR(255)" json:"mb_email"`
	MbHomepage      *string    `gorm:"column:mb_homepage;type:VARCHAR(255)" json:"mb_homepage"`
	MbLevel         *int32     `gorm:"column:mb_level;type:INTEGER" json:"mb_level"`
	MbSex           *string    `gorm:"column:mb_sex;type:VARCHAR(1)" json:"mb_sex"`
	MbBirth         *string    `gorm:"column:mb_birth;type:VARCHAR(255)" json:"mb_birth"`
	MbTel           *string    `gorm:"column:mb_tel;type:VARCHAR(255)" json:"mb_tel"`
	MbHp            *string    `gorm:"column:mb_hp;type:VARCHAR(255)" json:"mb_hp"`
	MbCertify       *string    `gorm:"column:mb_certify;type:VARCHAR(20)" json:"mb_certify"`
	MbAdult         *int32     `gorm:"column:mb_adult;type:INTEGER" json:"mb_adult"`
	MbDupinfo       *string    `gorm:"column:mb_dupinfo;type:VARCHAR(255)" json:"mb_dupinfo"`
	MbZip1          *string    `gorm:"column:mb_zip1;type:VARCHAR(3)" json:"mb_zip1"`
	MbZip2          *string    `gorm:"column:mb_zip2;type:VARCHAR(3)" json:"mb_zip2"`
	MbAddr1         *string    `gorm:"column:mb_addr1;type:VARCHAR(255)" json:"mb_addr1"`
	MbAddr2         *string    `gorm:"column:mb_addr2;type:VARCHAR(255)" json:"mb_addr2"`
	MbAddr3         *string    `gorm:"column:mb_addr3;type:VARCHAR(255)" json:"mb_addr3"`
	MbAddrJibeon    *string    `gorm:"column:mb_addr_jibeon;type:VARCHAR(255)" json:"mb_addr_jibeon"`
	MbSignature     *string    `gorm:"column:mb_signature;type:TEXT" json:"mb_signature"`
	MbRecommend     *string    `gorm:"column:mb_recommend;type:VARCHAR(255)" json:"mb_recommend"`
	MbPoint         *int32     `gorm:"column:mb_point;type:INTEGER" json:"mb_point"`
	MbTodayLogin    *time.Time `gorm:"column:mb_today_login;type:DATETIME" json:"mb_today_login"`
	MbLoginIP       *string    `gorm:"column:mb_login_ip;type:VARCHAR(255)" json:"mb_login_ip"`
	MbDatetime      *time.Time `gorm:"column:mb_datetime;type:DATETIME" json:"mb_datetime"`
	MbIP            *string    `gorm:"column:mb_ip;type:VARCHAR(255)" json:"mb_ip"`
	MbLeaveDate     *string    `gorm:"column:mb_leave_date;type:VARCHAR(8)" json:"mb_leave_date"`
	MbInterceptDate *string    `gorm:"column:mb_intercept_date;type:VARCHAR(8)" json:"mb_intercept_date"`
	MbEmailCertify  *time.Time `gorm:"column:mb_email_certify;type:DATETIME" json:"mb_email_certify"`
	MbEmailCertify2 *string    `gorm:"column:mb_email_certify2;type:VARCHAR(255)" json:"mb_email_certify2"`
	MbMemo          *string    `gorm:"column:mb_memo;type:TEXT" json:"mb_memo"`
	MbLostCertify   *string    `gorm:"column:mb_lost_certify;type:VARCHAR(255)" json:"mb_lost_certify"`
	MbMailling      *int32     `gorm:"column:mb_mailling;type:INTEGER" json:"mb_mailling"`
	MbSms           *int32     `gorm:"column:mb_sms;type:INTEGER" json:"mb_sms"`
	MbOpen          *int32     `gorm:"column:mb_open;type:INTEGER" json:"mb_open"`
	MbOpenDate      *time.Time `gorm:"column:mb_open_date;type:DATE" json:"mb_open_date"`
	MbProfile       *string    `gorm:"column:mb_profile;type:TEXT" json:"mb_profile"`
	MbMemoCall      *string    `gorm:"column:mb_memo_call;type:VARCHAR(255)" json:"mb_memo_call"`
	MbMemoCnt       *int32     `gorm:"column:mb_memo_cnt;type:INTEGER" json:"mb_memo_cnt"`
	MbScrapCnt      *int32     `gorm:"column:mb_scrap_cnt;type:INTEGER" json:"mb_scrap_cnt"`
	Mb1             *string    `gorm:"column:mb_1;type:VARCHAR(255)" json:"mb_1"`
	Mb2             *string    `gorm:"column:mb_2;type:VARCHAR(255)" json:"mb_2"`
	Mb3             *string    `gorm:"column:mb_3;type:VARCHAR(255)" json:"mb_3"`
	Mb4             *string    `gorm:"column:mb_4;type:VARCHAR(255)" json:"mb_4"`
	Mb5             *string    `gorm:"column:mb_5;type:VARCHAR(255)" json:"mb_5"`
	Mb6             *string    `gorm:"column:mb_6;type:VARCHAR(255)" json:"mb_6"`
	Mb7             *string    `gorm:"column:mb_7;type:VARCHAR(255)" json:"mb_7"`
	Mb8             *string    `gorm:"column:mb_8;type:VARCHAR(255)" json:"mb_8"`
	Mb9             *string    `gorm:"column:mb_9;type:VARCHAR(255)" json:"mb_9"`
	Mb10            *string    `gorm:"column:mb_10;type:VARCHAR(255)" json:"mb_10"`
}

// TableName Member's table name
func (*Member) TableName() string {
	return Prefix + TableNameMember
}
