// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMenu = "menu"

// Menu mapped from table <menu>
type Menu struct {
	MeID        *int32  `gorm:"column:me_id;type:INTEGER" json:"me_id"`
	MeCode      *string `gorm:"column:me_code;type:VARCHAR(255)" json:"me_code"`
	MeName      *string `gorm:"column:me_name;type:VARCHAR(255)" json:"me_name"`
	MeLink      *string `gorm:"column:me_link;type:VARCHAR(255)" json:"me_link"`
	MeTarget    *string `gorm:"column:me_target;type:VARCHAR(255)" json:"me_target"`
	MeOrder     *int32  `gorm:"column:me_order;type:INTEGER" json:"me_order"`
	MeUse       *int32  `gorm:"column:me_use;type:INTEGER" json:"me_use"`
	MeMobileUse *int32  `gorm:"column:me_mobile_use;type:INTEGER" json:"me_mobile_use"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return Prefix + TableNameMenu
}
