// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/dukhyungkim/gonuboard/config"
	"time"
)

const TableNameNewWin = "new_win"

// NewWin mapped from table <new_win>
type NewWin struct {
	NwID           *int32     `gorm:"column:nw_id;type:INTEGER" json:"nw_id"`
	NwDivision     *string    `gorm:"column:nw_division;type:VARCHAR(10)" json:"nw_division"`
	NwDevice       *string    `gorm:"column:nw_device;type:VARCHAR(10)" json:"nw_device"`
	NwBeginTime    *time.Time `gorm:"column:nw_begin_time;type:DATETIME" json:"nw_begin_time"`
	NwEndTime      *time.Time `gorm:"column:nw_end_time;type:DATETIME" json:"nw_end_time"`
	NwDisableHours *int32     `gorm:"column:nw_disable_hours;type:INTEGER" json:"nw_disable_hours"`
	NwLeft         *int32     `gorm:"column:nw_left;type:INTEGER" json:"nw_left"`
	NwTop          *int32     `gorm:"column:nw_top;type:INTEGER" json:"nw_top"`
	NwHeight       *int32     `gorm:"column:nw_height;type:INTEGER" json:"nw_height"`
	NwWidth        *int32     `gorm:"column:nw_width;type:INTEGER" json:"nw_width"`
	NwSubject      *string    `gorm:"column:nw_subject;type:TEXT" json:"nw_subject"`
	NwContent      *string    `gorm:"column:nw_content;type:TEXT" json:"nw_content"`
	NwContentHTML  *int32     `gorm:"column:nw_content_html;type:INTEGER" json:"nw_content_html"`
}

// TableName NewWin's table name
func (*NewWin) TableName() string {
	return config.Global.DbTablePrefix + TableNameNewWin
}
