// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePoll = "poll"

// Poll mapped from table <poll>
type Poll struct {
	PoID      *int32     `gorm:"column:po_id;type:INTEGER" json:"po_id"`
	PoSubject *string    `gorm:"column:po_subject;type:VARCHAR(255)" json:"po_subject"`
	PoPoll1   *string    `gorm:"column:po_poll1;type:VARCHAR(255)" json:"po_poll1"`
	PoPoll2   *string    `gorm:"column:po_poll2;type:VARCHAR(255)" json:"po_poll2"`
	PoPoll3   *string    `gorm:"column:po_poll3;type:VARCHAR(255)" json:"po_poll3"`
	PoPoll4   *string    `gorm:"column:po_poll4;type:VARCHAR(255)" json:"po_poll4"`
	PoPoll5   *string    `gorm:"column:po_poll5;type:VARCHAR(255)" json:"po_poll5"`
	PoPoll6   *string    `gorm:"column:po_poll6;type:VARCHAR(255)" json:"po_poll6"`
	PoPoll7   *string    `gorm:"column:po_poll7;type:VARCHAR(255)" json:"po_poll7"`
	PoPoll8   *string    `gorm:"column:po_poll8;type:VARCHAR(255)" json:"po_poll8"`
	PoPoll9   *string    `gorm:"column:po_poll9;type:VARCHAR(255)" json:"po_poll9"`
	PoCnt1    *int32     `gorm:"column:po_cnt1;type:INTEGER" json:"po_cnt1"`
	PoCnt2    *int32     `gorm:"column:po_cnt2;type:INTEGER" json:"po_cnt2"`
	PoCnt3    *int32     `gorm:"column:po_cnt3;type:INTEGER" json:"po_cnt3"`
	PoCnt4    *int32     `gorm:"column:po_cnt4;type:INTEGER" json:"po_cnt4"`
	PoCnt5    *int32     `gorm:"column:po_cnt5;type:INTEGER" json:"po_cnt5"`
	PoCnt6    *int32     `gorm:"column:po_cnt6;type:INTEGER" json:"po_cnt6"`
	PoCnt7    *int32     `gorm:"column:po_cnt7;type:INTEGER" json:"po_cnt7"`
	PoCnt8    *int32     `gorm:"column:po_cnt8;type:INTEGER" json:"po_cnt8"`
	PoCnt9    *int32     `gorm:"column:po_cnt9;type:INTEGER" json:"po_cnt9"`
	PoEtc     *string    `gorm:"column:po_etc;type:VARCHAR(255)" json:"po_etc"`
	PoLevel   *int32     `gorm:"column:po_level;type:INTEGER" json:"po_level"`
	PoPoint   *int32     `gorm:"column:po_point;type:INTEGER" json:"po_point"`
	PoDate    *time.Time `gorm:"column:po_date;type:DATE" json:"po_date"`
	PoIps     *string    `gorm:"column:po_ips;type:TEXT" json:"po_ips"`
	MbIds     *string    `gorm:"column:mb_ids;type:TEXT" json:"mb_ids"`
	PoUse     *int32     `gorm:"column:po_use;type:INTEGER" json:"po_use"`
}

// TableName Poll's table name
func (*Poll) TableName() string {
	return TableNamePoll
}
