// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePopular = "popular"

// Popular mapped from table <popular>
type Popular struct {
	PpID   *int32     `gorm:"column:pp_id;type:INTEGER" json:"pp_id"`
	PpWord *string    `gorm:"column:pp_word;type:VARCHAR(50)" json:"pp_word"`
	PpDate *time.Time `gorm:"column:pp_date;type:DATE" json:"pp_date"`
	PpIP   *string    `gorm:"column:pp_ip;type:VARCHAR(50)" json:"pp_ip"`
}

// TableName Popular's table name
func (*Popular) TableName() string {
	return TableNamePopular
}
