// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQaContent = "qa_content"

// QaContent mapped from table <qa_content>
type QaContent struct {
	QaID        *int32     `gorm:"column:qa_id;type:INTEGER" json:"qa_id"`
	QaNum       *int32     `gorm:"column:qa_num;type:INTEGER" json:"qa_num"`
	QaParent    *int32     `gorm:"column:qa_parent;type:INTEGER" json:"qa_parent"`
	QaRelated   *int32     `gorm:"column:qa_related;type:INTEGER" json:"qa_related"`
	MbID        *string    `gorm:"column:mb_id;type:VARCHAR(20)" json:"mb_id"`
	QaName      *string    `gorm:"column:qa_name;type:VARCHAR(255)" json:"qa_name"`
	QaEmail     *string    `gorm:"column:qa_email;type:VARCHAR(255)" json:"qa_email"`
	QaHp        *string    `gorm:"column:qa_hp;type:VARCHAR(255)" json:"qa_hp"`
	QaType      *int32     `gorm:"column:qa_type;type:INTEGER" json:"qa_type"`
	QaCategory  *string    `gorm:"column:qa_category;type:VARCHAR(255)" json:"qa_category"`
	QaEmailRecv *int32     `gorm:"column:qa_email_recv;type:INTEGER" json:"qa_email_recv"`
	QaSmsRecv   *int32     `gorm:"column:qa_sms_recv;type:INTEGER" json:"qa_sms_recv"`
	QaHTML      *int32     `gorm:"column:qa_html;type:INTEGER" json:"qa_html"`
	QaSubject   *string    `gorm:"column:qa_subject;type:VARCHAR(255)" json:"qa_subject"`
	QaContent   *string    `gorm:"column:qa_content;type:TEXT" json:"qa_content"`
	QaStatus    *int32     `gorm:"column:qa_status;type:INTEGER" json:"qa_status"`
	QaFile1     *string    `gorm:"column:qa_file1;type:VARCHAR(255)" json:"qa_file1"`
	QaSource1   *string    `gorm:"column:qa_source1;type:VARCHAR(255)" json:"qa_source1"`
	QaFile2     *string    `gorm:"column:qa_file2;type:VARCHAR(255)" json:"qa_file2"`
	QaSource2   *string    `gorm:"column:qa_source2;type:VARCHAR(255)" json:"qa_source2"`
	QaIP        *string    `gorm:"column:qa_ip;type:VARCHAR(255)" json:"qa_ip"`
	QaDatetime  *time.Time `gorm:"column:qa_datetime;type:DATETIME" json:"qa_datetime"`
	Qa1         *string    `gorm:"column:qa_1;type:VARCHAR(255)" json:"qa_1"`
	Qa2         *string    `gorm:"column:qa_2;type:VARCHAR(255)" json:"qa_2"`
	Qa3         *string    `gorm:"column:qa_3;type:VARCHAR(255)" json:"qa_3"`
	Qa4         *string    `gorm:"column:qa_4;type:VARCHAR(255)" json:"qa_4"`
	Qa5         *string    `gorm:"column:qa_5;type:VARCHAR(255)" json:"qa_5"`
}

// TableName QaContent's table name
func (*QaContent) TableName() string {
	return Prefix + TableNameQaContent
}
