// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQaConfig = "qa_config"

// QaConfig mapped from table <qa_config>
type QaConfig struct {
	ID                  *int32  `gorm:"column:id;type:INTEGER" json:"id"`
	QaTitle             *string `gorm:"column:qa_title;type:VARCHAR(255)" json:"qa_title"`
	QaCategory          *string `gorm:"column:qa_category;type:VARCHAR(255)" json:"qa_category"`
	QaSkin              *string `gorm:"column:qa_skin;type:VARCHAR(255)" json:"qa_skin"`
	QaMobileSkin        *string `gorm:"column:qa_mobile_skin;type:VARCHAR(255)" json:"qa_mobile_skin"`
	QaUseEmail          *int32  `gorm:"column:qa_use_email;type:INTEGER" json:"qa_use_email"`
	QaReqEmail          *int32  `gorm:"column:qa_req_email;type:INTEGER" json:"qa_req_email"`
	QaUseHp             *int32  `gorm:"column:qa_use_hp;type:INTEGER" json:"qa_use_hp"`
	QaReqHp             *int32  `gorm:"column:qa_req_hp;type:INTEGER" json:"qa_req_hp"`
	QaUseSms            *int32  `gorm:"column:qa_use_sms;type:INTEGER" json:"qa_use_sms"`
	QaSendNumber        *string `gorm:"column:qa_send_number;type:VARCHAR(255)" json:"qa_send_number"`
	QaAdminHp           *string `gorm:"column:qa_admin_hp;type:VARCHAR(255)" json:"qa_admin_hp"`
	QaAdminEmail        *string `gorm:"column:qa_admin_email;type:VARCHAR(255)" json:"qa_admin_email"`
	QaUseEditor         *int32  `gorm:"column:qa_use_editor;type:INTEGER" json:"qa_use_editor"`
	QaSubjectLen        *int32  `gorm:"column:qa_subject_len;type:INTEGER" json:"qa_subject_len"`
	QaMobileSubjectLen  *int32  `gorm:"column:qa_mobile_subject_len;type:INTEGER" json:"qa_mobile_subject_len"`
	QaPageRows          *int32  `gorm:"column:qa_page_rows;type:INTEGER" json:"qa_page_rows"`
	QaMobilePageRows    *int32  `gorm:"column:qa_mobile_page_rows;type:INTEGER" json:"qa_mobile_page_rows"`
	QaImageWidth        *int32  `gorm:"column:qa_image_width;type:INTEGER" json:"qa_image_width"`
	QaUploadSize        *int32  `gorm:"column:qa_upload_size;type:INTEGER" json:"qa_upload_size"`
	QaInsertContent     *string `gorm:"column:qa_insert_content;type:TEXT" json:"qa_insert_content"`
	QaIncludeHead       *string `gorm:"column:qa_include_head;type:VARCHAR(255)" json:"qa_include_head"`
	QaIncludeTail       *string `gorm:"column:qa_include_tail;type:VARCHAR(255)" json:"qa_include_tail"`
	QaContentHead       *string `gorm:"column:qa_content_head;type:TEXT" json:"qa_content_head"`
	QaContentTail       *string `gorm:"column:qa_content_tail;type:TEXT" json:"qa_content_tail"`
	QaMobileContentHead *string `gorm:"column:qa_mobile_content_head;type:TEXT" json:"qa_mobile_content_head"`
	QaMobileContentTail *string `gorm:"column:qa_mobile_content_tail;type:TEXT" json:"qa_mobile_content_tail"`
	Qa1Subj             *string `gorm:"column:qa_1_subj;type:VARCHAR(255)" json:"qa_1_subj"`
	Qa2Subj             *string `gorm:"column:qa_2_subj;type:VARCHAR(255)" json:"qa_2_subj"`
	Qa3Subj             *string `gorm:"column:qa_3_subj;type:VARCHAR(255)" json:"qa_3_subj"`
	Qa4Subj             *string `gorm:"column:qa_4_subj;type:VARCHAR(255)" json:"qa_4_subj"`
	Qa5Subj             *string `gorm:"column:qa_5_subj;type:VARCHAR(255)" json:"qa_5_subj"`
	Qa1                 *string `gorm:"column:qa_1;type:VARCHAR(255)" json:"qa_1"`
	Qa2                 *string `gorm:"column:qa_2;type:VARCHAR(255)" json:"qa_2"`
	Qa3                 *string `gorm:"column:qa_3;type:VARCHAR(255)" json:"qa_3"`
	Qa4                 *string `gorm:"column:qa_4;type:VARCHAR(255)" json:"qa_4"`
	Qa5                 *string `gorm:"column:qa_5;type:VARCHAR(255)" json:"qa_5"`
}

// TableName QaConfig's table name
func (*QaConfig) TableName() string {
	return Prefix + TableNameQaConfig
}
