// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/dukhyungkim/gonuboard/config"
	"time"
)

const TableNameScrap = "scrap"

// Scrap mapped from table <scrap>
type Scrap struct {
	MsID       *int32     `gorm:"column:ms_id;type:INTEGER" json:"ms_id"`
	MbID       *string    `gorm:"column:mb_id;type:VARCHAR(20)" json:"mb_id"`
	BoTable    *string    `gorm:"column:bo_table;type:VARCHAR(20)" json:"bo_table"`
	WrID       *int32     `gorm:"column:wr_id;type:INTEGER" json:"wr_id"`
	MsDatetime *time.Time `gorm:"column:ms_datetime;type:DATETIME" json:"ms_datetime"`
}

// TableName Scrap's table name
func (*Scrap) TableName() string {
	return config.Global.DbTablePrefix + TableNameScrap
}
