// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniqid = "uniqid"

// Uniqid mapped from table <uniqid>
type Uniqid struct {
	UqID *int64  `gorm:"column:uq_id;type:BIGINT" json:"uq_id"`
	UqIP *string `gorm:"column:uq_ip;type:VARCHAR(255)" json:"uq_ip"`
}

// TableName Uniqid's table name
func (*Uniqid) TableName() string {
	return Prefix + TableNameUniqid
}
