// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVisit = "visit"

// Visit mapped from table <visit>
type Visit struct {
	ViID      *int32     `gorm:"column:vi_id;type:INTEGER" json:"vi_id"`
	ViIP      *string    `gorm:"column:vi_ip;type:VARCHAR(100)" json:"vi_ip"`
	ViDate    *time.Time `gorm:"column:vi_date;type:DATE" json:"vi_date"`
	ViTime    *time.Time `gorm:"column:vi_time;type:TIME" json:"vi_time"`
	ViReferer *string    `gorm:"column:vi_referer;type:TEXT" json:"vi_referer"`
	ViAgent   *string    `gorm:"column:vi_agent;type:VARCHAR(200)" json:"vi_agent"`
	ViBrowser *string    `gorm:"column:vi_browser;type:VARCHAR(255)" json:"vi_browser"`
	ViOs      *string    `gorm:"column:vi_os;type:VARCHAR(255)" json:"vi_os"`
	ViDevice  *string    `gorm:"column:vi_device;type:VARCHAR(255)" json:"vi_device"`
}

// TableName Visit's table name
func (*Visit) TableName() string {
	return Prefix + TableNameVisit
}
